# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ad04622b2ba54ab025a6b9871d19762fd8d9fac14c665ea8962e053f81f514bd6b7c66b4f8f319e507354fed73e58fede61c135234cf3f8cfc29614554fa6e8a

test:
  secret_key_base: b02a79e45ed37700ba3c59d8b95b8341c754133e1bfedd1d2d4b2c3bf1248c5aba7ccba2c3b819a92bf2d15f62d1707f1d3ea1f1096dd0ef08dbade76b82501e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
